version: "3.9"

services:
  db:
    image: postgres:16
    container_name: yoga-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yoga_db
    ports:
      - "5432:5432"
    volumes:
      - yoga_pg_data:/var/lib/postgresql/data

volumes:
  yoga_pg_data:
